// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu189NHyhMjqqqiKCelRjuYEfNfDt7UJ8',
    appId: '1:137102747395:web:ab7b4bd61bcf64e6d9ab36',
    messagingSenderId: '137102747395',
    projectId: 'ccs-compass-8b019',
    authDomain: 'ccs-compass-8b019.firebaseapp.com',
    storageBucket: 'ccs-compass-8b019.firebasestorage.app',
    measurementId: 'G-GFNKEB9D29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_OntfgFMpmSsHA7SUS4kiVCxomzvbAz8',
    appId: '1:137102747395:android:ee635e78e0777d7ed9ab36',
    messagingSenderId: '137102747395',
    projectId: 'ccs-compass-8b019',
    storageBucket: 'ccs-compass-8b019.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUOeW6cngQzKEMzrJnpAFB2HSdEnD6IA8',
    appId: '1:137102747395:ios:83c2041cbcd79930d9ab36',
    messagingSenderId: '137102747395',
    projectId: 'ccs-compass-8b019',
    storageBucket: 'ccs-compass-8b019.firebasestorage.app',
    iosBundleId: 'com.example.ccsCompass',
  );
}
